# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://wittmannf.github.io/covid19br/"

git_url = "https://github.com/wittmannf/covid19br/tree/master/"

def custom_doc_links(name): return None
